import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useRef} from "react"
import LoadScroll from "iath-infinitescroll";
export default function Home() {
  const mainRef=useRef(0)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Infinitescroll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main ref={mainRef} className={styles.main}>
        {
          Array.from(Array(10).keys()).map((e,i)=>{
            return <h6>This is a Item </h6>
          })
        }
      </main>

      
    </div>
  )
}
